-- EP01 - CAMADA SILVER
-- Modelo dimensional em estrela.
-- Grão da fato: uma linha representa a participação de um Pokémon em um combate.

CREATE SCHEMA IF NOT EXISTS silver;

CREATE TABLE IF NOT EXISTS silver.dim_pokemon (
    pokemon_sk              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_csv_id          INTEGER NOT NULL UNIQUE,
    pokeapi_pokemon_id      INTEGER UNIQUE,
    pokedex_especie_id      INTEGER,

    nome_csv                TEXT,
    nome_api                TEXT,
    nome_exibicao           TEXT NOT NULL,
    conciliado              BOOLEAN NOT NULL,
    estrategia_conciliacao  TEXT NOT NULL,
    is_default              BOOLEAN,
    forma_alternativa       BOOLEAN NOT NULL DEFAULT FALSE,

    tipo_primario           TEXT NOT NULL,
    tipo_secundario         TEXT,
    geracao_num             SMALLINT NOT NULL CHECK (geracao_num BETWEEN 1 AND 6),
    geracao_nome            TEXT NOT NULL,
    regiao                  TEXT NOT NULL,

    hp                      SMALLINT NOT NULL,
    ataque                  SMALLINT NOT NULL,
    defesa                  SMALLINT NOT NULL,
    ataque_especial         SMALLINT NOT NULL,
    defesa_especial         SMALLINT NOT NULL,
    velocidade              SMALLINT NOT NULL,

    altura_m                NUMERIC(8,2),
    peso_kg                 NUMERIC(8,2),
    experiencia_base        INTEGER,
    quantidade_habilidades  SMALLINT,

    habitat                 TEXT,
    habitat_situacao        TEXT NOT NULL CHECK (
        habitat_situacao IN ('INFORMADO', 'NAO_APLICAVEL', 'DADO_AUSENTE', 'DESCONHECIDO')
    ),
    cor                     TEXT,
    forma_corporal          TEXT,
    taxa_crescimento        TEXT,
    taxa_captura            SMALLINT,
    felicidade_base         SMALLINT,

    lendario_csv            BOOLEAN NOT NULL,
    is_legendary            BOOLEAN,
    is_mythical             BOOLEAN,
    is_baby                 BOOLEAN,
    raridade                TEXT NOT NULL CHECK (
        raridade IN ('COMUM', 'BEBE', 'LENDARIO', 'MITICO', 'DESCONHECIDO')
    )
);

CREATE TABLE IF NOT EXISTS silver.dim_tipo (
    tipo_sk             SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokeapi_tipo_id     INTEGER UNIQUE,
    nome                TEXT NOT NULL UNIQUE,
    membro_especial     BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS silver.dim_geracao (
    geracao_sk      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero          SMALLINT NOT NULL UNIQUE CHECK (numero BETWEEN 1 AND 6),
    nome            TEXT NOT NULL UNIQUE,
    regiao          TEXT NOT NULL
);

-- Estrutura de apoio da Silver: matriz de efetividade 18 x 18.
-- Não é uma dimensão snowflake; é uma relação analítica entre dois papéis de dim_tipo.
CREATE TABLE IF NOT EXISTS silver.efetividade_tipo (
    tipo_atacante_sk    SMALLINT NOT NULL,
    tipo_defensor_sk    SMALLINT NOT NULL,
    multiplicador       NUMERIC(4,2) NOT NULL CHECK (multiplicador IN (0, 0.5, 1, 2)),
    PRIMARY KEY (tipo_atacante_sk, tipo_defensor_sk),
    CONSTRAINT fk_efetividade_atacante
        FOREIGN KEY (tipo_atacante_sk) REFERENCES silver.dim_tipo(tipo_sk),
    CONSTRAINT fk_efetividade_defensor
        FOREIGN KEY (tipo_defensor_sk) REFERENCES silver.dim_tipo(tipo_sk)
);

CREATE TABLE IF NOT EXISTS silver.fato_participacao (
    participacao_sk                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combate_id                      INTEGER NOT NULL,
    ordem_no_csv                    SMALLINT NOT NULL CHECK (ordem_no_csv IN (1, 2)),

    pokemon_sk                      BIGINT NOT NULL,
    oponente_sk                     BIGINT NOT NULL,
    tipo_primario_sk                SMALLINT NOT NULL,
    tipo_secundario_sk              SMALLINT NOT NULL,
    oponente_tipo_primario_sk       SMALLINT NOT NULL,
    oponente_tipo_secundario_sk     SMALLINT NOT NULL,
    geracao_sk                      SMALLINT NOT NULL,
    oponente_geracao_sk             SMALLINT NOT NULL,

    venceu                          SMALLINT NOT NULL CHECK (venceu IN (0, 1)),
    atacou_primeiro                 SMALLINT NOT NULL CHECK (atacou_primeiro IN (0, 1)),
    velocidade                      SMALLINT NOT NULL,
    velocidade_oponente             SMALLINT NOT NULL,
    diferenca_velocidade            SMALLINT NOT NULL,

    UNIQUE (combate_id, ordem_no_csv),

    CONSTRAINT fk_fato_pokemon
        FOREIGN KEY (pokemon_sk) REFERENCES silver.dim_pokemon(pokemon_sk),
    CONSTRAINT fk_fato_oponente
        FOREIGN KEY (oponente_sk) REFERENCES silver.dim_pokemon(pokemon_sk),
    CONSTRAINT fk_fato_tipo_primario
        FOREIGN KEY (tipo_primario_sk) REFERENCES silver.dim_tipo(tipo_sk),
    CONSTRAINT fk_fato_tipo_secundario
        FOREIGN KEY (tipo_secundario_sk) REFERENCES silver.dim_tipo(tipo_sk),
    CONSTRAINT fk_fato_oponente_tipo_primario
        FOREIGN KEY (oponente_tipo_primario_sk) REFERENCES silver.dim_tipo(tipo_sk),
    CONSTRAINT fk_fato_oponente_tipo_secundario
        FOREIGN KEY (oponente_tipo_secundario_sk) REFERENCES silver.dim_tipo(tipo_sk),
    CONSTRAINT fk_fato_geracao
        FOREIGN KEY (geracao_sk) REFERENCES silver.dim_geracao(geracao_sk),
    CONSTRAINT fk_fato_oponente_geracao
        FOREIGN KEY (oponente_geracao_sk) REFERENCES silver.dim_geracao(geracao_sk)
);

-- Artefato auditável exigido pelo R4. Ele substitui conciliacao.csv.
CREATE TABLE IF NOT EXISTS silver.log_conciliacao (
    pokemon_csv_id          INTEGER PRIMARY KEY,
    nome_csv                TEXT,
    nome_normalizado        TEXT,
    pokeapi_pokemon_id      INTEGER,
    nome_api                TEXT,
    pokedex_especie_id      INTEGER,
    status                  TEXT NOT NULL CHECK (
        status IN ('CONCILIADO', 'NOME_AUSENTE', 'NAO_CONCILIADO')
    ),
    estrategia              TEXT NOT NULL,
    detalhe                 TEXT
);

CREATE INDEX IF NOT EXISTS idx_fato_pokemon
    ON silver.fato_participacao (pokemon_sk);
CREATE INDEX IF NOT EXISTS idx_fato_oponente
    ON silver.fato_participacao (oponente_sk);
CREATE INDEX IF NOT EXISTS idx_fato_tipo
    ON silver.fato_participacao (tipo_primario_sk, oponente_tipo_primario_sk);
CREATE INDEX IF NOT EXISTS idx_fato_diferenca_velocidade
    ON silver.fato_participacao (diferenca_velocidade);
